# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.15.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
# Method 1
a=np.random.random((2,3,5))


In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [10]:
# your code here
print (a)

[[[0.08505874 0.29663617 0.31716293 0.92572102 0.34002617]
  [0.72335043 0.15893493 0.39069903 0.02142915 0.19002488]
  [0.44572354 0.34353649 0.49841638 0.57796044 0.13727527]]

 [[0.36385423 0.37327442 0.79625485 0.21991493 0.15625408]
  [0.19792572 0.95772605 0.713194   0.36131355 0.11911173]
  [0.85557845 0.38632313 0.67078237 0.59351833 0.43757   ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.full((5,2,3), 1)
print (b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 6. Print *b*.


In [20]:
print (b)
print(len(b))

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
5


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# your answer here
#No because they have the same size but are not equal in their construction
np.array_equal(a,b)

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print (b)
c=b.reshape(2,3,5)
print (c)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
# your code/answer here
# Works now because they have the same structure
a.size==c.size
d=np.add(a,c)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
# your code/answer here
#all values of d are the values of a +1 since we added c with all values =1 to a.

print(a)
print(d)

[[[0.29045588 0.31158254 0.26360239 0.73416522 0.72563684]
  [0.97812331 0.1819382  0.07824029 0.91761977 0.20460118]
  [0.88238456 0.09821945 0.1895989  0.68622681 0.2560349 ]]

 [[0.05829973 0.53791648 0.49405036 0.93189705 0.61810571]
  [0.47448618 0.27261795 0.82399182 0.84757433 0.29880357]
  [0.90030069 0.10182052 0.36531458 0.75206259 0.20802524]]]
[[[1.29045588 1.31158254 1.26360239 1.73416522 1.72563684]
  [1.97812331 1.1819382  1.07824029 1.91761977 1.20460118]
  [1.88238456 1.09821945 1.1895989  1.68622681 1.2560349 ]]

 [[1.05829973 1.53791648 1.49405036 1.93189705 1.61810571]
  [1.47448618 1.27261795 1.82399182 1.84757433 1.29880357]
  [1.90030069 1.10182052 1.36531458 1.75206259 1.20802524]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
e=np.multiply(a, c)


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# Yes e==a since we multiplied every number of a by 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
# your code here
d_mean=np.mean(d)
d_max=np.max(d)
d_min=np.min(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [36]:
# your code here
f=np.empty([2,3,5])
print (f)

[[[0.29045588 0.31158254 0.26360239 0.73416522 0.72563684]
  [0.97812331 0.1819382  0.07824029 0.91761977 0.20460118]
  [0.88238456 0.09821945 0.1895989  0.68622681 0.2560349 ]]

 [[0.05829973 0.53791648 0.49405036 0.93189705 0.61810571]
  [0.47448618 0.27261795 0.82399182 0.84757433 0.29880357]
  [0.90030069 0.10182052 0.36531458 0.75206259 0.20802524]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [66]:
# your code here
temp=[]
for block in d:
    for row in block:
        for value in row:
            if value > d_min and value < d_mean:
                temp.append(25)
            elif value < d_max and value > d_mean:
                temp.append(75)
            elif value==d_min:
                temp.append(0)
            elif value ==d_max:
                temp.append(100)
#Used a list temp to append to then turned it into an array
# and reshape into the right form
# Couldn´t directly add to f
res=np.array(temp)
f=res.reshape(2,3,5)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [67]:
# your code here
print (d)
print (f)

[[[1.29045588 1.31158254 1.26360239 1.73416522 1.72563684]
  [1.97812331 1.1819382  1.07824029 1.91761977 1.20460118]
  [1.88238456 1.09821945 1.1895989  1.68622681 1.2560349 ]]

 [[1.05829973 1.53791648 1.49405036 1.93189705 1.61810571]
  [1.47448618 1.27261795 1.82399182 1.84757433 1.29880357]
  [1.90030069 1.10182052 1.36531458 1.75206259 1.20802524]]]
[[[ 25  25  25  75  75]
  [100  25  25  75  25]
  [ 75  25  25  75  25]]

 [[  0  75  75  75  75]
  [ 25  25  75  75  25]
  [ 75  25  25  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [69]:
# your code here
temp=[]
for block in d:
    for row in block:
        for value in row:
            if value > d_min and value < d_mean:
                temp.append("B")
            elif value < d_max and value > d_mean:
                temp.append("C")
            elif value==d_min:
                temp.append("A")
            elif value ==d_max:
                temp.append("D")
#Used a list temp to append to then turned it into an array
# and reshape into the right form
# Couldn´t directly add to f
res=np.array(temp)
f=res.reshape(2,3,5)# your code here
print (f)

[[['B' 'B' 'B' 'C' 'C']
  ['D' 'B' 'B' 'C' 'B']
  ['C' 'B' 'B' 'C' 'B']]

 [['A' 'C' 'C' 'C' 'C']
  ['B' 'B' 'C' 'C' 'B']
  ['C' 'B' 'B' 'C' 'B']]]
